project_id = "pticjnptiyhpworwfsxf"

[functions.admin-users]
verify_jwt = false

[functions.audit-log]
verify_jwt = false

[functions.manage-portal-user]
verify_jwt = false

[functions.bootstrap]
verify_jwt = false

[functions.gamify-api]
verify_jwt = false
